files/config/routes.rb
<%= app_name.camelize %>::Application.routes.draw do

  resources :users,   only: [:new, :create]
  resource  :session, only: [:new, :create, :destroy]

  get    'register',  to: 'users#new'
  get    'signin',    to: 'sessions#new'
  delete 'signout',   to: 'sessions#destroy'

  root to: 'pages#home'

end

files/app/models/user.rb
class User < ActiveRecord::Base

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = %r(\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z)i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  before_create :generate_authentication_token

  def self.authenticate(email, password)
    find_by(email: email).try(:authenticate, password)
  end

  private

    def generate_authentication_token
      begin
        self.authentication_token = SecureRandom.urlsafe_base64
      end while User.exists?(authentication_token: self.authentication_token)
    end
end

files/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authenticatable
  protect_from_forgery
end

files/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @page = localized_page unless signed_in?
  end

  private

    def localized_page
      "#{Rails.root}/config/locales/#{controller_name}/"\
        "#{action_name}/#{action_name}.#{I18n.locale}.md"
    end
end

files/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    if user = User.authenticate(params[:session][:email],
                                params[:session][:password])
      sign_in user
      flash[:success] = t('flash.successful_sign_in')
      redirect_to root_url
    else
      flash.now[:error] = t('flash.invalid_credentials')
      render 'new'
    end
  end

  def destroy
    sign_out
    flash[:success] = t('flash.successful_sign_out')
    redirect_to root_url
  end
end

files/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :deny, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = t('flash.successful_registration')
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

files/app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = t('layouts.application.base_title')
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

files/app/views/layouts/_footer.html.haml
%footer.footer
  %small
    = t('.author')

files/app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  .navbar-inner
    .container
      .brand
        = link_to t('.<%= app_name %>'), root_path
      %nav
        %ul.nav.pull-right
          %li
            = link_to root_path do
              %i.icon-home
              = t('.home')
          - if signed_in?
            %li
              = link_to signout_path, method: :delete do
                %i.icon-signout
                = t('.sign_out')
          - else
            %li
              = link_to signin_path do
                %i.icon-signin
                = t('.sign_in')
            %li
              = link_to register_path do
                %i.icon-group
                = t('.register')

files/app/views/layouts/_messages.html.haml
- flash.each do |name, message|
  %div{ class: "alert alert-#{name}" }
    %a.close{ "data-dismiss" => "alert" } ×
    = content_tag(:div, message, id: "flash_#{name}")

files/app/views/layouts/_shim.html.haml
/ [if lt IE 9]
  %script(src="http://html5shim.googlecode.com/svn/trunk/html15.js")

files/app/views/pages/_home_not_signed_in.html.haml
.text-center.hero-unit
  :markdown
    #{render file: page}

files/app/views/pages/_home_signed_in.html.haml
.text-center
  %h1= t('.heading')

  %p
    This is dynamic content for the Home Page, which you can see if you're
    logged in.

  %p
    You can find this page at
    %code
      app/views/pages/_home_signed_in.html.haml

files/app/views/pages/home.html.haml
- if signed_in?
  = render 'home_signed_in'
- else
  = render 'home_not_signed_in', page: @page

files/app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      %a.close{ "data-dismiss" => "alert" } ×
      = t('.form_errors')

files/app/views/users/_registration_form.html.haml
= simple_form_for(user, html: {class: 'form-vertical' }) do |f|
  = render 'shared/error_messages', object: f.object
  = f.input :name
  = f.input :email
  = f.input :password, label: t('.password')
  = f.input :password_confirmation, label: t('.password_confirmation')
  .checkbox
    = f.input :remember_me, as: :boolean, label: false do
      = check_box_tag :remember_me, 1, true
      = label_tag :remember_me
  = f.button :submit, t('.create_account'), class: "btn btn-large btn-primary"

files/app/views/users/new.html.haml
= provide(:title, t('.register'))
.text-center
  %h1= t('.register')
.row
  .span6.offset3
    = render 'registration_form', user: @user